app = 'gotrip-sv'
primary_region = 'eze'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = "512mb"
  size = 'shared-cpu-1x'

[env]
  # Critical JVM memory settings
  JAVA_OPTS = "-Xmx256m -Xss512k -XX:MaxRAM=512m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError"
  
  # Ensure Spring knows it's in production
  SPRING_PROFILES_ACTIVE = "prod"

[deploy]
  min_machines = 1